# Generated by Django 4.1.7 on 2023-03-06 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sd_projects', '0003_alter_comment_author_alter_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, help_text='Author of the commentary', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of creation of the commentary'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(help_text='Short commentary content', max_length=320),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(help_text='Issue to which this commentary is mapped', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sd_projects.issue'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'read'), (2, 'write'), (3, 'delete')], help_text='\nPermission of the contributor for the project\n- 1: Read only\n- 2: Read, Write\n- 3: Read, Write and Delete\n'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(help_text='Project of which this contributor is contributing to', on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='sd_projects.project'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'owner'), (2, 'contributor')], help_text='\nRole of the contributor for the project\n- 1: Owner\n- 2: Contributor\n'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='user',
            field=models.ForeignKey(help_text='User being the actual contributor', on_delete=django.db.models.deletion.CASCADE, related_name='contributing_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned',
            field=models.ForeignKey(help_text='Contributor assigned to solving the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(default=1, help_text='Author of the issue', on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of creation of the issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(help_text='Short description of the issue', max_length=320),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'low'), (1, 'average'), (2, 'high')], help_text='\nPriority of the issue\n- 0: Low\n- 1: Average\n- 2: High\n'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(help_text='Project to which this issue is mapped', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='sd_projects.project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'todo'), (1, 'pending'), (2, 'finished')], help_text='\nStatus of the issue\n- 0: Todo\n- 1: Pending\n- 2: Finished\n'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.PositiveSmallIntegerField(choices=[(0, 'bug'), (1, 'improvement'), (2, 'task')], help_text='\nTag attributed to the issue\n- 0: Bug\n- 1: Improvement\n- 2: Task\n'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text='Title of the issue', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default=1, help_text='Author of the project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, help_text='Short description of the project', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Title of the project', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'back-end'), (1, 'front-end'), (2, 'iOS'), (3, 'android')], help_text='\nType of the project\n- 0: Back-end\n- 1: Front-end\n- 2: iOS\n- 3: Android\n', verbose_name='type'),
        ),
    ]
