# Generated by Django 4.1.7 on 2023-03-07 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sd_projects', '0004_alter_comment_author_alter_comment_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned',
            field=models.ForeignKey(default=None, help_text='Contributor assigned to solving the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
