# Generated by Django 4.1.7 on 2023-03-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_projects', '0005_alter_issue_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'owner'), (2, 'contributor')], default=2, help_text='\nRole of the contributor for the project\n- 1: Owner\n- 2: Contributor\n'),
        ),
    ]
